version: "3.2"
# docker compose version for compatibility with CircleCI
services:
  s3:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - HOSTNAME=localhost
      - DEFAULT_REGION=eu-central-1
    ports:
      - "4566:4566"
